---
version: '3'
services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: intelliqit
    deploy:
      replicas: 2

  mywordpress:
    image: wordpress
    ports:
      - 8080:80
    deploy:
      replicas: 3
...        
