apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mydb
  name: mydb
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mydb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: intelliqit
        image: mysql:5
        name: mydb
        resources: {}
      restartPolicy: Always
status: {}
