---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: worker-app-deployment
 labels:
  name: worker-app
  author: intelliqit
spec:
  selector:
   matchLabels:
    name: worker-app
  template:
   metadata:
    name: worker-app-pod
    labels:
     name: worker-app
   spec:
    containers:
     - name: my-worker-app
       image: dockersamples/examplevotingapp_worker
...

 


